### ISSUE TITLE
Event Types discrepancy between Docs and API for DTC Codes

### ISSUE THREAD

**Issue by galenandrew** [vinli/vinli-node#15]
I am receiving the following error message from the Vinli API which conflicts with the documentation for [Creating a Subscription](http://docs.vin.li/en/latest/web/API-reference/index.html#create-a-subscription).

Which DTC event types are correct?

---

#### DTC Event Types (per [Vinli Documentation](http://docs.vin.li/en/latest/web/event-services/overview.html#event-types))
- `dtc-code-detect`
- `dtc-code-clear`

#### DTC Event Types (per API error message)
- `dtc-on`
- `dtc-off`

_API Response:_
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"subscription\" fails because [child \"eventType\" fails because [\"eventType\" must be one of [rule-enter, rule-leave, rule-*, startup, shutdown, collision, dtc-on, dtc-off, trip-*, trip-started, trip-stopped, trip-orphaned, trip-completed]]]"
}
```

**Comment by kturney** [comment]
dtc-on and dtc-off are the correct event types. We will update the docs. Thanks.
