### ISSUE TITLE
[Question] Cascading deletes when deregistering a device?

### ISSUE THREAD

**Issue by galenandrew** [vinli/vinli-node#16]
Context: Let's say I have an _enterprise_ app with a registered device that has event subscriptions…

**When calling the [Deregister a Device](http://docs.vin.li/en/latest/web/API-reference/index.html#deregister-a-device) endpoint, do these event subscriptions also get deleted?**

**Comment by kturney** [comment]
@galenandrew the answer is they should, but it looks like they currently do not.
I'm going to open a bug on our internal services.

**Comment by galenandrew** [comment]
:metal:
