### ISSUE TITLE
[Feature Request] Include `caseId` in response when registering a device by ID

### ISSUE THREAD

**Issue by galenandrew** [vinli/vinli-node#17]
**Context**
The API supports registering a device via `caseId` or `id` ([reference](https://github.com/vinli/vinli-node/blob/master/lib/app.js#L8-L11)). When registering with a Case ID the response includes both `id` and `caseId` ([reference](https://github.com/vinli/vinli-node/blob/master/test/app_tests.js#L124)), however when registering the device by ID the response _does not_ include `caseId`.

---

### Desired Functionality
It would be helpful for the response to return both `id` and `caseId` regardless of which parameter is used to register the device.

_This will help developers retain parity between a device ID and Case ID within their applications._

**Example Request**
```
POST https://platform.vin.li/api/v1/devices
Content-Type: application/json

{
  "device" : {
    "id" : "821374c0-d6d8-11e3-9c1a-0800200c9a66",
  }
}
```
_- or -_
```
POST https://platform.vin.li/api/v1/devices
Content-Type: application/json

{
  "device" : {
    "caseId" : "VNL999"
  }
}
```

**Example Response**
```
HTTP/1.1 201 CREATED
Content-Type: application/json
Location: https://platform.vin.li/api/v1/devices/821374c0-d6d8-11e3-9c1a-0800200c9a66

{
  "device" : {
    "id" : "821374c0-d6d8-11e3-9c1a-0800200c9a66",
    "caseId" : "VNL999",
    "links" : {...}
  }
}
```

---

_Related: Including `caseId` in the get device details response would be very helpful too!<br>i.e. `GET https://platform.vin.li/api/v1/devices/821374c0-d6d8-11e3-9c1a-0800200c9a66`_

**Comment by kturney** [comment]
We actually do not want devs to have regular access to or use the case ID. Case ID is  for customers to show physical access to the device. Devs should always use the returned device ID. The customer facing info would be the device name, if they've set it. An enterprise customer could set the device's name to the case ID if they so desired. (At least after we implement names for enterprise devices. I'll create a bug.)

**Comment by galenandrew** [comment]
Makes sense…thanks for the reply @kturney!
